"""add department, id_number and phone_number

Revision ID: 490fe951a771
Revises: 7141312a71d0
Create Date: 2025-07-13 09:45:25.288313

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '490fe951a771'
down_revision = '7141312a71d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('id_number', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('id_number')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
