"""Remove attachment field from Activity model

Revision ID: 5d3d566ff9c4
Revises: 5676608384a7
Create Date: 2025-07-17 13:53:19.556946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d3d566ff9c4'
down_revision = '5676608384a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_column('attachment')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attachment', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
